### ISSUE TITLE
version mismatch of released version and `aws-mfa-login --version`

### ISSUE THREAD

**Issue by cruschke** [signavio/aws-mfa-login#9]
When downloading the latest v0.12 release and running a `aws-mfa-login --version`, it presents `aws-mfa-login version 0.1.1` expecting a `0.12` here.

**Comment by karlderkaefer** [comment]
should work now better in future. the lastest version is
```
aws-mfa-login --version
aws-mfa-login version 0.1.3
```

**Comment by cruschke** [comment]
works on my machine :-)
